s = 'bccdddeeeeeeeee'
print(s.count('c'), end = '')
print(s.count('a'), end = '')
print(s.count('b'), end = '')
print(s.count('e'), end = '')
print(s.count('a'), end = '')
print(s.count('e'), end = '')
print(s.count('c'), end = '')
print(s.count('d'), end = '')